Gemfile.lock
config/routes.rb

Change root path

---

Gemfile.lock
app/controllers/questions_controller.rb
app/views/questions/index.html.erb
app/views/questions/show.html.erb

#7 
・permitにuser_nameを追加
・viewに投稿者を表示
　qusestions/showに投稿者を表示させる
　qusestions/indexに投稿者を表示させる
questionでレコードを作成している方は、一度DBのレコードをクリアしてください。
```
rails c
>Question.delete_all
```

[Fixed] Issue#7-2 質問に投稿者の名前を紐付けて表示できるようにする

---

Gemfile.lock
app/models/question.rb
app/models/user.rb
app/models/vote.rb
db/migrate/20171225045914_create_votes.rb
db/schema.rb
test/fixtures/votes.yml
test/models/vote_test.rb

#3 
・voteモデルの作成
・voteテーブル（中間テーブル）の作成
・アソシエーションの設定
変更箇所は以上です。
よろしくお願いします。

voteテーブルの作成

---

Gemfile.lock
app/controllers/users_controller.rb
app/views/users/index.html.erb
test/controllers/users_controller_test.rb

#2-1 usersコントローラー設定(index、show)
ユーザー一覧ページ、ユーザー詳細ページ用、
usersコントローラー作成
・使用機能
index（ユーザー一覧）、allにてユーザーデータ全取得
show（ユーザー詳細）、idからfind使用し、個人データを取得

#2-1usersコントローラー設定(index、show)

---

Gemfile.lock
app/controllers/users_controller.rb
app/views/users/index.html.erb
config/routes.rb
test/controllers/users_controller_test.rb

#2-2 routes.rb設定(index、show)
resources :users, only: [:index, :show]を追記
注意点として、
devise_for :usersの下にある事が必要なため、下部に追記しております。

#2-2ユーザー一覧、詳細用routing設定(index,show)

---

app/views/questions/index.html.erb
app/views/questions/show.html.erb

#7 
・ qusestions/showに投稿日時を表示させる
・qusestions/indexに投稿時間を表示させる

[Fixed]issue#7-4 質問投稿時間の表示をする

---

app/views/questions/index.html.erb
app/views/questions/show.html.erb

#7 
投稿者だけが自身の質問の編集・削除を実施できる
ログインしていない場合は、編集・削除リンクを表示しない

[Fixed]#7-3 質問を編集・削除できるのは投稿者だけにする

---

app/assets/javascripts/lists/tags.coffee
app/assets/stylesheets/lists/tags.scss
app/controllers/lists/tags_controller.rb
app/helpers/lists/tags_helper.rb
app/views/questions/_form.html.erb
app/views/questions/_tag_list.html.erb
app/views/questions/index.html.erb
app/views/questions/show.html.erb
config/routes.rb
test/controllers/lists/tags_controller_test.rb

#5-3 質問投稿の際に、タグを選択して一緒に保存できるようにする をプルリクします。確認お願いします。
実際にローカルで動かしてみていただくと簡単に把握できると思いますのでよろしくお願いします！

Issue#5-3 質問投稿の際に、タグを選択して一緒に保存できるようにする

---

db/migrate/20180101072103_add_index_to_vote.rb
db/schema.rb

votesテーブルにindexを追加

---

app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

ログイン画面、新規登録画面のレイアウトを修正

---

app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/views/users/index.html.erb
app/views/users/show.html.erb

#2-4 view作成(show)
・usersコントローラー
showアクションに追記
questionモデルより、
where(user_id:　params [:id])とし、
一致する質問を全取得
・show.html.erb(view)
画像　名前　各貢献度
質問一覧表示部分は、questionのindexからソース毎借りました。
・他修正
index.html.erb、無駄な空白の修正
■今後、頭の中で考えてる内容
取得データふえちゃうけど、
「質問一覧」と「お気に入り一覧」、JSあたりでぱっと切り替えれたらいいのか悩み中
いったんお気に入り作成に入ります。

#2-4 view作成(show)

---

app/views/devise/registrations/edit.html.erb

#1-2
view/devise/registration/edit.html.erb
パスワード変更等のボタン動作、修正
1DIVの閉め位置を修正

【fixed】deviseページの変更承認ボタンエラー修正

---

app/views/devise/registrations/edit.html.erb

#1-2
view/devise/registration/edit.html.erb
パスワード変更等の更新ボタン、動作せずを解消
1</div>の移動のみ

【fixed】 view/devise/registration/edit.html.erb htmlソース修正

---

app/views/answers/_index.html.erb
app/views/questions/index.html.erb

#6-4
以下を実施
・質問詳細画面に回答数を表示
・質問一覧に回答数を表示

[Fixed]#6-4 アンサー数の表示

---

app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/views/users/_question_list.html.erb
app/views/users/show.html.erb

#4-3 マイページにお気に入り一覧
・users/show.html.erb
にお気に入り一覧を表示
@check_listでどの一覧か、取得データを判定
取得データの有無により、パーシャル（リスト書き出し）or　質問投稿無しを返す
・パーシャル（リスト書き出し）
インスタンス変数をeachメソッド
→questionに格納
→パーシャルへ
で作成しています。
後々を考えると、変数処理もパーシャル内のほうが、
同html.erbソースを書かずにすむため、
if文の処理部分はパーシャルに移動させるかもしれません。

#4-3 マイページにお気に入り一覧

---

app/controllers/questions_controller.rb
app/controllers/votes_controller.rb

変更点
・自分の質問には投票出来ないように変更
・質問一覧を新着順で表示するよう変更
確認お願いします。

#3-3自分の質問には投票できないよう修正

---

app/controllers/users_controller.rb
app/views/users/_answer_list.html.erb
app/views/users/show.html.erb

[Fixed]#6-5 ユーザー詳細で表示したユーザーのアンサー一覧を見れるようにする

---

app/assets/javascripts/answers.coffee
app/assets/javascripts/questions.coffee
app/assets/javascripts/top.coffee
app/assets/javascripts/votes.coffee
app/helpers/answers_helper.rb
app/helpers/favorites_helper.rb
app/helpers/questions_helper.rb
app/helpers/top_helper.rb

assetsフォルダ
helperフォルダ
コメントのみのファイルを削除し、整理しました。

Issue#deletefile　不要ファイルの整理

---

app/controllers/users_controller.rb
app/views/users/index.html.erb
app/views/users/show.html.erb
db/seeds.rb

#2-5　(#4-7含む)
・ユーザー詳細
質問、お気に入り一覧にページネーション追加（20件）
取得データを一度、ローカル変数で格納し
ローカル格納した内容にページネーションで通りました。

#2-5-2 ページネーション追加、ユーザー詳細、質問とお気に入りにページネーション機能追加

---

app/controllers/users_controller.rb
app/views/users/index.html.erb
db/seeds.rb

#2-5　ユーザー一覧ページにページネーション追加
・gem　kaminari使用
1ページ最大20人表示
今回はソート無し（order指定無し）
・確認用seedデータを更新
10人→50人作成へ
nameをFaker::Name.name,に変更

#2-5　ユーザー一覧ページにページネーション追加

---

app/controllers/top_controller.rb
app/views/top/index.html.erb

#7 -1-1
Rootを質問一覧表示にしたのでTOPの情報を削除

[Fixed]#7-1-1 TOP ViewとControllerを削除

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb

Issue#1 3　マイページでプロフィールを追加できるよう修正

---

app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/views/users/_question_list.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb

#4-6
・上部、プロフィールタブ用意
・変数実装　質問数、回答数、登録日
・表示一覧パーシャルの投票、回答数実装
総計がうまくいかないです…

#4ｰ6　ユーザー詳細　デザイン修正

---

Gemfile
Gemfile.lock
app/assets/javascripts/question.coffee
app/controllers/questions_controller.rb
app/views/layouts/application.html.erb

gem"gon" 追加 
question編集画面で既存のタグを表示する
よろしくお願いします！

 issue#5-5 gem"gon" 追加 & question編集画面で既存のタグを表示する

---

app/controllers/answers_controller.rb
app/models/answer.rb
app/views/answers/edit.html.erb
app/views/answers/form.js.erb
app/views/answers/index.js.erb
app/views/questions/show.html.erb

#6 -9
[回答作成部分]
・controllers/answers_controller.rb
　回答作成viewはAjax対応にしているため、エラー時のレスポンスをjsにしてform.jsを呼ぶようにする
・views/answers/form.js.erb
　エラー時の内容をid = answer_formで表示するようにする処理を入れる
・views/answers/index.js.erb
　エラーメッセージを削除するようにする(エラー発生後に正しく値を入力して登録した際のエラークリア用)
・views/questions/show.html.erb
　formでのエラー表示用にdivでくくって、idを割り振る
[回答編集部分]
・views/questions/edit.html.erb
　前はformをrenderしていたが、editはajax化していないので一旦、分けて記載
（将来的にeditも動的に実装した際に処理を共通化していく予定）

[Fixed]#6-9 適切なバリデーションを設定すること 
